### PR TITLE
Fix ie detect.js remove, fixes #55 bug

### LINKED ISSUE #55: Uncaught TypeError: document.attachEvent is not a function
I use this plugin and get this error `Uncaught TypeError: document.attachEvent is not a function` in chrome and edge browser. Does any plugin missing here?

### PR DESCRIPTION
**Pull request by Chyngyz**
`ieVersion()` returns false for non-ie browsers, thus `if (!flexibility.detect() || ieVersion() <= 9)` becomes true and `document.attachEvent` gives `Uncaught TypeError: document.attachEvent is not a function` error. 
It should be `if (!flexibility.detect() && ieVersion() <= 9)`, I guess )
Tested in IE8-9, tests work fine.

### CODE REVIEW

**Comment by noahjohn9259** [comment]
Thanks!

**Comment by jonathantneal** [comment]
I’m not including detection in v2 at this time. I’m open to including it, but I recommend folks use Modernizr or their own detection. Think I should change this? We can open a new issue.

https://github.com/jonathantneal/flexibility/blob/master/SUPPORT.md#detecting-flexbox-support

**Comment by Dan503** [comment]
Nah I think using modernizr for the detection is the best way to do it. No need to add extra weight to handle detection when modern browsers shouldn't be loading the script at all in the first place.

**Comment by Dan503** [comment]
Is there a reason you haven't built the window resize functionality you have documented in the support md file into the main script itself?

If there aren't any common problems that occur from the window resize script, it should just be applied by default.

**Pull request closed without merging**
